interface: cli: Extract fetch-deps/merge-sboms doc strings to constants
Future patch will convert these strings to dynamically formatted ones
using f-strings based on the entrypoint that was used for the
application. Usage of f-strings in docstrings is discouraged, however,
flake8 doesn't really have a builtin rule for this (as there is no PEP)
for it, instead, it crashes when parsing the code:

    File "/usr/local/lib/python3.9/ast.py", line 71, in _convert_num
        _raise_malformed_node(node)
    File "/usr/local/lib/python3.9/ast.py", line 68, in _raise_malformed_node
        raise ValueError(f'malformed node or string: {node!r}')
    ValueError: malformed node or string: <ast.JoinedStr object at 0x7fcf81ad5580>

The proper fix here is to not rely on help messages for these commands
to be generated out of doc strings automatically, but supply them
as a parameter explicitly via the command decorator.

Take the opportunity and perform a tiny cosmetic formatting change to
the merge-sboms message by inserting \b backspace escapes to prevent
click's default text rewrapping [1].

[1] https://click.palletsprojects.com/en/stable/documentation/#preventing-rewrapping

Signed-off-by: Erik Skultety <eskultet@redhat.com>