Unify cargo config.toml file data for pip and cargo backends
Closes https://github.com/hermetoproject/hermeto/issues/1097

Hermeto generates a .cargo/config.toml for pip requests that pull in
Rust dependencies, redirecting crates.io to a vendored crate directory
under the output layout. Cargo requires that `replace-with` matches a
named [source.NAME] section.

The alias "local" is inconsistent with our cargo backend.

The «NAME» is just an aribtrary label. The following template would also
work:

```
[source.crates-io]
replace-with = "yolo"

[source.yolo]
directory = "${output_dir}/deps/cargo"
```

```
nox -s generate-test-data -- -k pip_e2e_rust
```

We need to keep it consistent because if one decides to have a Rust
project and Python project with Rust dependencies in one git repository,
then Cargo would complain about different sources (assuming they use
hermetic builds with Hermeto):

error: source `local` defines source dir /.../hermeto-output/deps/cargo, but that source is already defined by `vendored-sources`
      note: Sources are not allowed to be defined multiple times.

--
https://github.com/hermetoproject/hermeto/blob/main/hermeto/core/package_managers/cargo/main.py#L488
https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/config.rs#L257
https://doc.rust-lang.org/cargo/reference/source-replacement.html

Signed-off-by: Michal Šoltis <msoltis@redhat.com>