Revert "build(deps): bump backrefs from 5.9 to 6.0.1"
This reverts commit e2ddf643dcb21cc75df0b638ffea73796dd9f212.

One can't even create a virtual environment due to:
    ERROR: Cannot install -r requirements-extras.txt (line 687) and
    backrefs==6.0.1 because these package versions have conflicting
    dependencies.

    The conflict is caused by:
        The user requested backrefs==6.0.1
        mkdocs-material 9.6.16 depends on backrefs~=5.7.post1

Signed-off-by: Erik Skultety <eskultet@redhat.com>