gomod: Print the Git error message a failure to fetch tags happens
This is very useful when troubleshooting these types of errors.
Currently, the only printed output is this:

Error: FetchError: Failed to fetch the tags on the Git repository [...]

Which hides the underlying cause.

Signed-off-by: Bruno Pimentel <bpimente@redhat.com>