test: switched most integration test images to alpine
Some of the runtimes in images that were switched to Alpine had to be
update due to missing dependecies.

- cargo_e2e: rust (Alpine)
- generic_e2e_maven: eclipse-temurin (Alpine)

Rest of the image could not be bumped due to various errors.

Ruby (found no version with git installed):
  STEP 3/3: RUN . /tmp/hermeto.env && bundle install
  You need to install git to be able to use gems from git repositories. ...

Python (wheels-e2e):
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Error: building at STEP "RUN . /tmp/hermeto.env && \
  python3 -m pip install -r requirements.txt": while running runtime: exit status 1

closes https://github.com/hermetoproject/hermeto/issues/1241

Signed-off-by: Jakub Nekvinda <jnekvind@redhat.com>