.github: release: Drop 'fetch-tags' actions/checkout argument
When commit 005d7b83 added this setting it was based on a CodeRabbit AI
review suggestion which appeared to make sense, however, in practice
led to the following CI workflow failure:

    /usr/bin/git -c protocol.version=2 fetch --prune
    --no-recurse-submodules --depth=1 origin
    +b108bb4c2502d9179555be0db717766e5607e98c:refs/tags/0.41.0-alpha
    Error: fatal: Cannot fetch both
    b108bb4c2502d9179555be0db717766e5607e98c and refs/tags/0.41.0-alpha
    to refs/tags/0.41.0-alpha The process '/usr/bin/git' failed with
    exit code 128

Drop the argument, the CI action will checkout a specific ref which we
tagged via the native GitHub release process.

Signed-off-by: Erik Skultety <eskultet@redhat.com>
(cherry picked from commit 2ec59517729ed53864295f3cca0e0bb8b56d6d76)
Signed-off-by: Erik Skultety <eskultet@redhat.com>