package_managers: gomod: Provide a global base exec env for Go
We're stripping the subprocess environment for Go invocations
completely apart from the exact things we want the child environment
to have set. The problem is, Go might need some fundamental env vars on
top of that - HOME and PATH to derive the defaults for other env
variables like GOMODCACHE and GOPATH.

This problem surfaced in downstream Hermeto build where the same test
suite as we have in upstream failed with:

    go: module cache not found: neither GOMODCACHE nor GOPATH is set
    Error: PackageManagerError: Go execution failed:
    `/usr/local/go/go_latest/bin/go work edit -json` failed with rc=1

    OR

    go: module cache not found: neither GOMODCACHE nor GOPATH is set
    Error: PackageManagerError: Go execution failed:
    `/usr/local/go/go_latest/bin/go env GOVERSION` failed with rc=1

FWIW this was exhibited with the following UBI go-toolset image [1] but
not with an earlier version [2]. The exact specifics on what changed in
the UBI's go-toolset to surface this bug of ours is not important.

[1] registry.access.redhat.com/ubi10/go-toolset:1790644755
[2] registry.access.redhat.com/ubi10/go-toolset:1789986858

Assisted-by: Claude
Signed-off-by: Erik Skultety <eskultet@redhat.com>