tests: Update the base image for generic_e2e_maven tests
The ibmjava does not support arch arm64, which will cause the test
failure as follows on MacOS, and eclipse-temurin java works.

```
 Error: creating build container: choosing an image from manifest
 list docker://mirror.gcr.io/ibmjava:11-jdk: no image found in
 manifest list for architecture "arm64", variant "v8", OS "linux"
```

Signed-off-by: Wenjie Guo <wguo@redhat.com>